#Should allow Mayor and King grant the shop administrator permission on they town / nation.
allow-permission-override: true

#Should allow override the owner name from town/nation vault name to town/nation display name.
allow-owner-name-override: true

#If QS should ignore disabled worlds.
ignore-disabled-worlds: true

#Should we also check flags and other stuff even target world not enabled in Towny
whitelist-mode: true

#Should we send the taxes to the town/nation vault account if shop inside a town or nation.
#NOTE: If shop belongs to a Town or Nation, taxes will still send to Server taxes account.
taxes-to-town: true

#Should we delete player's shops in town when they leaved the that town
delete-shop-on-resident-leave: false
#Should we remove the shops in plot when plot cleared
delete-shop-on-plot-clear: true
#Should we remove the shops in plot when plot unclaimed
delete-shop-on-plot-unclaimed: true

#Which checks does a player need to pass to create a shop?
#You can use multiple checks at the same time.
#Priority: UP > DOWN
#
#Available fields:
#OWN = The player must own the plot to create a shop.
#MODIFY = The player must have the ability to build on the target plot to create a shop.
#SHOPTYPE = The player must create the shop on a SHOP type plot.
create:
  - SHOPTYPE
  - MODIFY
#Which checks does a player need to pass to trade with a shop?
#You can use multiple checks at the same time.
#Priority: UP > DOWN
#
#Available fields:
#OWN = The player must own the plot to trade with a shop.
#MODIFY = The player must have the ability to build on the target plot to trade with a shop.
#SHOPTYPE = The player must trade with the shop on a SHOP type plot.
trade: [ ]
