name: QuickShop-Hikari
main: com.ghostchu.quickshop.QuickShop
softdepend:
  - Vault
  - Reserve
  - PlaceholderAPI
  - LuckPerms
  - PermissionEx
  - GroupManager
  - Essentials
  - CMI
  - ProtocolLib
  - NBTAPI
api-version: 1.18
# TODO: https://github.com/PaperMC/Paper/pull/7177
libraries:
  - org.apache.commons:commons-compress:1.21
  - org.apache.commons:commons-lang3:3.12.0
  - org.apache.commons:commons-text:1.9
  - com.rollbar:rollbar-java:1.8.1
  - commons-codec:commons-codec:1.15
  - org.slf4j:slf4j-nop:1.7.35
  - cc.carm.lib:easysql-hikaricp:0.4.2
  - com.h2database:h2:2.1.214
  - com.ghostchu:simplereloadlib:1.1.2
  - com.konghq:unirest-java:3.13.7
  - com.github.juliomarcopineda:jdbc-stream:0.1.1
  - one.util:streamex:0.8.1
  - commons-lang:commons-lang:2.6
  - net.sourceforge.csvjdbc:csvjdbc:1.0.40
authors:
  - Ghost_chu
  - PotatoCraft Studio
  - Netherfoam
  - Timtower
  - KaiNoMood (KaiKikuchi)
  - jho5245
  - cakoyo
  - Ectabro
  - portlek
  - log4b0at
  - Andre601
  - deadman96385
  - Vlvxingze
  - DoctaEnkoda
  - Mgazul
  - TiaraRinne
  - sandtechnology
  - Starmism
  - Chris6ix
  - Rean Schwarzer
  - mart-r
  - raphtaliapt
  - Tim269
  - creatorfromhell
  - LoneDev6
  - judgetread
  - confuxeon
  - ibmibmibm
  - yannicklamprecht
  - PyvesB
  - PaulBGD
  - ORelio
  - JoschuaSchneider
  - Starmium
  - harry0198
  - Draesia
  - Nlkomaru
  - Warriorrrr
description: Economy Shops plugin

version: ${project.version}
commands:
  qs:
    description: QuickShop command
    usage: /qs
    aliases: [ qsshop,qshop,quickshop ]

permissions:
  quickshop.player:
    description: The permission that provide all player need have permissions
    default: op
    children:
      quickshop.use: true
      quickshop.create.sell: true
      quickshop.create.buy: true
      quickshop.create.stacks: true
      quickshop.create.changeitem: true
      quickshop.create.changeamount: true
      quickshop.create.changeprice: true
      quickshop.create.double: true
      quickshop.create.cmd: true
      quickshop.transfer: true
      quickshop.find: true
      quickshop.fetchmessage: true
      quickshop.staff: true
      quickshop.preview: true
      quickshop.currency: true
      quickshop.toggledisplay: true
      quickshop.shopnaming: true
      quickshop.permission: true
  quickshop.moderator:
    description: The permission that provide all moderator need have permissions
    default: op
    children:
      quickshop.other.destroy: true
      quickshop.other.open: true
      quickshop.other.price: true
      quickshop.bypass.*: true
      quickshop.alerts: true
      quickshop.create.admin: true
      quickshop.other.changeitem: true
      quickshop.other.changeamount: true
      quickshop.other.staff: true
      quickshop.other.currency: true
      quickshop.other.taxaccount: true
      quickshop.other.toggledisplay: true
      quickshop.purge: true
      quickshop.other.setowner: true
      quickshop.taxaccount: true
      quickshop.other.shopnaming: true
      quickshop.bypass.namefee: true
      quickshop.other.search: true
      quickshop.other.preview: true
      quickshop.other.use: true

  quickshop.create.sell:
    description: Allows a player to sell from a shop.
    default: op
  quickshop.create.buy:
    description: Allows a player to buy from a shop.
    default: op
  quickshop.create.double:
    description: Allows a player to create a double shop.
    default: op
  quickshop.create.changeprice:
    description: Allows a player to change their shop's price.
    default: op
  quickshop.create.cmd:
    description: Allows a player to use /qs create to create a shop.
    default: op
  quickshop.create.admin:
    description: Allows a player use /qs supercreate to create a shop that bypasses all protection checks.
    default: op
  quickshop.create.changeitem:
    description: Allows a player to change their shop's item.
    default: op
  quickshop.create.changeamount:
    description: Allows a player to change their shop's item amount per trade.
    default: op
  quickshop.create.stacks:
    description: Allows a player to create a shop with stacked items.
    default: op
  quickshop.use:
    description: Allows a player to buy/sell using other player's shops.
    default: true
  quickshop.unlimited:
    description: Allows a staff member to use /qs unlimited to make a shop infinite.
    default: op
  quickshop.alwayscounting:
    description: Allows a staff member to use /qs alwayscounting to make a shop always counting container.
    default: op
  quickshop.bypass.<itemID>:
    description: Allows a player to sell blacklisted <itemIDs>.
    default: op
  quickshop.other.destroy:
    description: Allows a staff member to destroy other player's shops even if they are locked.
    default: op
  quickshop.other.open:
    description: Allows a staff member to open someone else's shop even if it is locked.
    default: op
  quickshop.other.price:
    description: Allows a staff member to change the price of someone else's shop.
    default: op
  quickshop.other.item:
    description: Allows a staff member to change the item of someone else's shop.
    default: op
  quickshop.other.amount:
    description: Allows a staff member to change the item amount per trade of someone else's shop.
    default: op
  quickshop.setowner:
    description: Allows a staff member to change the owner of any shop.
    default: op
  quickshop.staff:
    description: Allows a shop owner to manage their shop staff.
    default: op
  quickshop.other.staff:
    description: Allows a other player force editing the shop staffs.
    default: op
  quickshop.find:
    description: Allows a player to locate the nearest shop that has a specific item type. Distance configurable in config.
    default: true
  quickshop.refill:
    description: Allows a staff member to refill the shop they're looking at with the given number of items.
    default: op
  quickshop.empty:
    description: Allows a staff member to empty the shop they're looking at of all items.
    default: op
  quickshop.debug:
    description: Enables developer mode.
    default: op
  quickshop.export:
    description: Allows exporting the database to a plain file.
    default: op
  quickshop.alerts:
    description: Recieve cheat alerts, plugin warnings and update notifications.
    default: op
  quickshop.about:
    description: Show QuickShop's about message.
    default: true
  quickshop.info:
    description: Show QuickShop's Statistics.
    default: op
  quickshop.fetchmessage:
    description: Allows the use of the /qs fetchmessage command to manually fetch shop messages from the database. Will not effect auto fetch if turned on...
    default: true
  quickshop.paste:
    description: Allows the use of the /qs paste command to upload server information to Pastebin. !WARNING! This will upload your data and may leak your server configuration and other sensitive information.
    default: op
  quickshop.preview:
    description: Permission to preview item using a GUI.
    default: true
  quickshop.tax:
    description: Permission to bypass taxes.
    default: op
  quickshop.tax.bypassunlimited:
    description: Permission to bypass taxes but for unlimited shops ONLY.
    default: op
  quickshop.cleanghost:
    description: Permission to use /qs cleanghost.
    default: op
  quickshop.reset:
    description: Permission to use /qs reset.
    default: op
  quickshop.bypasscreatefee:
    description: Permission to bypass the creation fee.
    default: op
  quickshop.recovery:
    description: Permission to use /qs recovery. !WARNING! DO NOT EXECUTE THIS COMMAND IF YOU DON'T KNOW WHAT YOU'RE DOING.
    default: op
  quickshop.removeall.other:
    description: Permission to use /qs removeall <player> to remove other player's shops.
    default: op
  quickshop.removeall.self:
    description: Permission to use /qs removeall to remove player's own shops.
    default: op
  quickshop.removeworld:
    description: Permission to use /qs removeworld.
    default: op
  quickshop.currency:
    description: Permission to use /qs currency.
    default: op
  quickshop.other.currency:
    description: Permission to use /qs currency but for other's shops.
    default: op
  quickshop.showdisabled:
    description: Permission to see disabled commands in help list.
    default: op
  quickshop.taxaccount:
    description: Permission to use /qs taxaccount
    default: op
  quickshop.other.taxaccount:
    description: Permission to use /qs taxaccount on others shops
    default: op
  quickshop.toggledisplay:
    description: Permission to use /qs toggledisplay
    default: op
  quickshop.other.toggledisplay:
    description: Permission to use /qs toggledisplay on others shops
    default: op
  quickshop.purge:
    description: Permission to use /qs purge
    default: op
  quickshop.shopnaming:
    description: Permission to use /qs name
    default: op
  quickshop.other.shopnaming:
    description: Permission to use /qs name on others shops
    default: op
  quickshop.bypass.namefee:
    description: Permission to use /qs name without the fee
    default: op
  quickshop.permission:
    description: Permission to use /qs permission
    default: op
  quickshop.other.search:
    description: Permission to bypass the search flag restriction
    default: op
  quickshop.other.preview:
    description: Permission to bypass the shop preview restriction
    default: op
  quickshop.other.use:
    description: Permission to bypass the purchase restriction
    default: op
  quickshop.database:
    description: Permission to use /qs database
    default: op
