name: qscompat-${project.artifactId}
version: '${project.version}'
main: com.ghostchu.quickshop.compatibility.${project.artifactId}.Main
api-version: 1.18
depend:
  - QuickShop-Hikari
softdepend:
  - Geyser
  - Floodgate
authors: [ Ghost_chu ]
description: Compatibility module for ClearLagg
