# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Upload

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 21
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package -T 1.5C --file pom.xml
      - uses: actions/upload-artifact@v4.4.0
        with:
          name: QuickShop-Hikari-Snapshots
          path: |
            quickshop-bukkit/target/QuickShop-Hikari-*.jar
